### ISSUE TITLE
[vo=dmabuf-wayland] Can't play any video, playback results in black window and 'failed to import' errors

### ISSUE THREAD

**Issue by syncrond** [mpv-player/mpv#10842]
### Important Information

Provide following Information:
- mpv version
  - git HEAD, ffmpeg git HEAD libplacebo git HEAD

```
mpv 0.34.0-578-g2e5d0d6e07 Copyright © 2000-2022 mpv/MPlayer/mplayer2 projects
 built on Wed Nov  9 16:26:23 CET 2022
FFmpeg library versions:
   libavutil       57.42.100
   libavcodec      59.52.100
   libavformat     59.34.101
   libswscale      6.8.112
   libavfilter     8.50.100
   libswresample   4.9.100
FFmpeg version: N-109036-g10ddbaf514

```
- Linux Distribution and Version
  - Ubuntu 22.10 
  - Linux kernel 6.0
  - mesa 23.0.0-devel
- Window Manager and version
  - GNOME 43 wayland session
- GPU driver and version
  - `inxi -Ga`
```
Graphics:
  Device-1: Intel Iris Plus Graphics 640 driver: i915 v: kernel arch: Gen-9.5
    process: Intel 14nm built: 2016-20 ports: active: DP-2 empty: DP-1,HDMI-A-1
    bus-ID: 00:02.0 chip-ID: 8086:5926 class-ID: 0300
  Device-2: Realtek Cable Matters USB-C Video type: USB driver: N/A
    bus-ID: 3-1:2 chip-ID: 0bda:5442 class-ID: 1100 serial: 123456789ABCDEFGH
  Display: wayland server: X.org v: 1.21.1.4 with: Xwayland v: 22.1.3
    compositor: gnome-shell v: 43.0 driver: X: loaded: modesetting
    unloaded: fbdev,vesa gpu: i915 display-ID: 0
  Monitor-1: DP-2 model: Dell U3219Q serial: 4SKPWP2 built: 2019
    res: 3840x2160 dpi: 140 gamma: 1.2 size: 697x392mm (27.44x15.43")
    diag: 800mm (31.5") ratio: 16:9 modes: max: 3840x2160 min: 720x400
  OpenGL: renderer: Mesa Intel Iris Plus Graphics 640 (Kaby Lake GT3e) (KBL
    GT3) v: 4.6 Mesa 23.0.0-devel (git-7753e80 2022-11-06 kinetic-oibaf-ppa)
    direct render: Yes
```

### Reproduction steps

Play a video with: 
`mpv -v --no-config --vo=dmabuf-wayland --hwdec=vaapi ~/<any_video>.mp4`

results in mpv opening a black window and logging constantly:

```
[   0.911][v][vo/dmabuf-wayland] Allocate buffer pool entry : 21
[   0.911][v][vo/dmabuf-wayland] NV12(0100000000000002) is not supported.
[   0.911][v][vo/dmabuf-wayland] Failed to import
[   0.911][v][vo/dmabuf-wayland] Free buffer pool entry : 21
```

If I try it without hwdec:

`mpv -v --no-config --vo=dmabuf-wayland --hwdec=no ~/<any_video>.mp4`

results in the same black window but with a different error message:
```
[e][ffmpeg] AVHWFramesContext: Failed to write image to surface 0x1: -1 (unknown libva error)
```

### Expected behavior

Video plays back.

### Actual behavior

Mpv just opens a window with no content.

### Log file

https://0x0.st/o6zZ.txt

with `hwdec=no`:

https://0x0.st/o6zN.txt

### Sample files

Any video on my side.
