### ISSUE TITLE
mpv crashes on Fedora 35 + GNOME + Wayland + Nvidia

### ISSUE THREAD

**Issue by Paveloom** [mpv-player/mpv#9393]
### Important Information

- **mpv version**:  0.34.0
- **Linux Distribution and Version**: Fedora Linux 35
- **Source of the mpv binary**: RPM package (0.34.0-1.fc35)
- **Window Manager and version**: GNOME 41.1
- **GPU driver and version**:
  ```
  Graphics:
    Device-1: Intel Skylake GT2 [HD Graphics 520] driver: i915 v: kernel 
    Device-2: NVIDIA GM108M [GeForce 940MX] driver: nvidia v: 495.44 
    Device-3: Cheng Uei Precision Industry (Foxlink) XiaoMi USB 2.0 Webcam 
    type: USB driver: uvcvideo 
    Display: wayland server: X.Org 1.21.1.2 driver: loaded: intel,nvidia 
    unloaded: fbdev,modesetting,nouveau,vesa resolution: 1920x1080~60Hz 
    OpenGL: renderer: Mesa Intel HD Graphics 520 (SKL GT2) v: 4.6 Mesa 21.2.5
  ```

### Reproduction steps

1. Try to play any file.

### Expected behavior

mpv plays the file.

### Actual behavior

mpv crashes with

```
 (+) Video --vid=1 (*) (h264 1280x720 24.000fps)
 (+) Audio --aid=1 (*) (aac 2ch 44100Hz)
[vo/gpu/wayland] GNOME's wayland compositor lacks support for the idle inhibit protocol. This means the screen can blank during playback.
AO: [pulse] 44100Hz stereo 2ch float
VO: [gpu] 1280x720 yuv420p
[destroyed object]: error 7: failed to import supplied dmabufs: Arguments are inconsistent (for example, a valid context requires buffers not supplied by a 
[vo/gpu/wayland] Error occurred on the display fd, closing

Exiting... (Quit)
```

### Log file

[log.txt](https://github.com/mpv-player/mpv/files/7474202/log.txt)

### Notes

This is most likely an upstream issue, but I think it needs to be documented.
